- name: Install and Configure Mysql Database
  hosts: db_servers
  gather_facts: true
  become: true
  vars:
    root_password: sekhar
    db_name: "sekhar"
    db_user: "sekhar"
    db_user_password: "db_password"
  tasks:
   - name: install the db_servers
     